apiVersion: v1
kind: Pod
metadata:
  name: banco-mysql
  labels:
    app: banco-mysql
spec:
  containers:
    - name: banco-mysql-container
      image: mysql:5.6
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: banco-mysql
  ports:
    - port: 3306
      #targetPort: <Target Port>
      nodePort: 30005
