apiVersion: v1
kind: Pod
metadata:
  name: servico-nginx
  labels:
    app: servico-nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: NodePort
  selector:
    app: servico-nginx
  ports:
    - port: 80
      #targetPort: <Target Port>
      nodePort: 30006
